# vm_hostname: change it as per your vm's hostname(not mandatory. you can set it any string)
# vm_public-IP: Public IP of your Virtual-Machine
# path_to_ssh_key: enter the path of the ssh key that you are using with your VM
# you can add `N` number of hosts in this file.
all:
  hosts:
    vm1_hostname:
      ansible_connection: ssh
      ansible_host: "vm1_public-IP"
      ansible_port: 22
      ansible_user: root
      #ansible_password: "xxxx" # not required if using ssh key
      ansible_ssh_private_key_file: "path_to_ssh_key"
      ansible_python_interpreter: "/usr/bin/python3"
   
    vm2_hostname:
      ansible_connection: ssh
      ansible_host: "vm2_public-IP"
      ansible_port: 22
      ansible_user: root
      #ansible_password: "xxxx" # not required if using ssh key
      ansible_ssh_private_key_file: "path_to_ssh_key"
      ansible_python_interpreter: "/usr/bin/python3"
